version: '3'
services:
  activemq:
    image: rmohr/activemq
    ports:
      - "61616:61616"   # JMS Port
      - "8161:8161"     # Admin Console Port
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin

#  spring-boot-app:
#    build: .
#    ports:
#      - "8080:8080"     # Spring Boot Application Port
#    depends_on:
#      - activemq
